server:
  port: ${PORT:8080}
  context-path: /api

#app:
#  auth:
#    token:
#      secret-key: ${AUTH_TOKEN_SECRET_KEY}
#      refresh-cookie-key: ${ AUTH_TOKEN_REFRESH_COOKIE_KEY}


spring:
  profiles:
    active:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_NAME}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  data:
    web:
      pageable:
        default-page-size: 5
        one-indexed-parameters: true

  jpa:
    show-sql: true
    database: mysql
    open-in-view: false
    dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create   #create update none
      default_batch_fetch_size: 500
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            redirect-uri: ${KAKAO_REDIRECT_URI}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
#cloud:
#  aws:
#    credentials:
#      instance-profile: false
#      access-key: ${EC2_S3_ACCESS_KEY}
#      secret-key: ${EC2_S3_SECRET_KEY}
#    region:
#      auto: false
#      static: ap-northeast-2
#    stack:
#      auto: false
jwt:
  secret: ${JWT_SECRET}


logging:
  level:
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG

